name: schemaflow
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - pip
  - pip:
      - antlr4-python3-runtime>=4.13.2
      - bitsandbytes>=0.46.1
      - datasets>=5.0.0
      - peft>=0.19.1
      - transformers>=5.12.1
      - -e .